const FETCH_POSTS = 'FETCH_POSTS';
const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';
const CLEAR_POSTS_ERRORS = 'CLEAR_POSTS_ERRORS';

export {
  FETCH_POSTS,
  FETCH_POSTS_FULFILLED,
  FETCH_POSTS_REJECTED,
  CLEAR_POSTS_ERRORS,
}